import { createSlice } from "@reduxjs/toolkit"; // Importing createSlice from Redux Toolkit
import { list } from "./data"; // Importing initial movie data from a local file
import { useSelector } from "react-redux"; // Importing useSelector from react-redux for accessing state

const initialState = {
  movieList: [...list], // Initial state with an array to store movie data
};

// Creating a slice of state for movies
const movieSlice = createSlice({
  name: "movies", // Slice name
  initialState, // Initial state defined above
  reducers: {
    // Reducers for modifying state
    addMovie(state, action) {
      state.movieList.unshift(action.payload); // Adding a new movie to the beginning of the list
    },
    editMovie(state, action) {
      state.movieList.splice(action.payload, 1);
      // Adding a new movie to the beginning of the list
    },
    removeMovie(state, action) {
      state.movieList = state.movieList.filter(
        (movie, i) => i !== action.payload
      ); // Removing a movie from the list based on index
    },
    addRating(state, action) {
      const movies = [...state.movieList];
      movies[action.payload.index].YouRated = action.payload.count; // Adding or updating a rating for a movie
    },
    addReview(state, action) {
      const movies = [...state.movieList];
      movies[action.payload.index].YouReview = action.payload.text; // Adding or updating a review for a movie
    },
    toggleWatch(state, action) {
      const movies = [...state.movieList];
      movies[action.payload].Watched = !movies[action.payload].Watched; // Toggling the watched status of a movie
    },
    // Add other reducers as needed for edit, delete, watch status, rating, etc.
  },
});

// Exporting actions generated by createSlice
export const {
  addMovie,
  addRating,
  removeMovie,
  toggleWatch,
  addReview,
  editMovie,
} = movieSlice.actions;

// Exporting the reducer function created by createSlice
const movieReducer = movieSlice.reducer;

// Selector function to access the movieList state from the Redux store
export const movieListSelector = (state) => state.movies.movieList;

export default movieReducer; // Exporting the reducer function for use in the Redux store
